// Read/write the Rocinante .env file (ROCINANTE_SECRET and ROCINANTE_AUTH_ENABLED).
//
// Layout: one key=value per line, `#` comments, no quoting. We hand-roll a
// parser because the only env vars we touch are the two keys above; pulling
// in `dotenv` for a 40-line file would be overkill.
//
// Why this lives at the package root: Next.js auto-loads .env from the CWD
// the launcher spawns it with, and the launcher sets CWD to the package
// root (bin/rocinante.js:92). Writing here means the next process restart
// sees the change with no custom loader.

import { randomBytes } from "node:crypto";
import { chmodSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { clearAllRevocations } from "./auth-token";

const SECRET_KEY = "ROCINANTE_SECRET";
const ENABLED_KEY = "ROCINANTE_AUTH_ENABLED";
const HEADER = `# Generated by Rocinante. Do not edit by hand unless you know what
# you're doing — see docs/in-progress/2026-08-13-access-key-protection.md
`;

export interface EnvState {
  hasSecret: boolean;
  enabled: boolean;
  path: string;
}

function defaultEnvPath(): string {
  if (process.env.ROCINANTE_ENV_PATH) return resolve(process.env.ROCINANTE_ENV_PATH);
  return resolve(process.cwd(), ".env");
}

export function readEnvFile(path: string = defaultEnvPath()): EnvState {
  if (!existsSync(path)) {
    return { hasSecret: false, enabled: false, path };
  }
  const text = readFileSync(path, "utf8");
  const lines = text.split(/\r?\n/);
  let hasSecret = false;
  let enabled = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("#") || trimmed.length === 0) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    if (key === SECRET_KEY && value.length > 0) hasSecret = true;
    if (key === ENABLED_KEY && (value.toLowerCase() === "true" || value === "1")) enabled = true;
  }
  return { hasSecret, enabled, path };
}

function parseLines(text: string): Array<{ key: string; value: string; line: string }> {
  const out: Array<{ key: string; value: string; line: string }> = [];
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (trimmed.length === 0) {
      out.push({ key: "", value: "", line });
      continue;
    }
    if (trimmed.startsWith("#")) {
      out.push({ key: "", value: "", line });
      continue;
    }
    const eq = trimmed.indexOf("=");
    if (eq === -1) {
      out.push({ key: "", value: "", line });
      continue;
    }
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1);
    out.push({ key, value, line });
  }
  return out;
}

function renderEnvFile(state: { secret: string; enabled: boolean }): string {
  return `${HEADER}${SECRET_KEY}=${state.secret}\n${ENABLED_KEY}=${state.enabled ? "true" : "false"}\n`;
}

export function generateSecret(): string {
  return randomBytes(32).toString("base64");
}

export interface WriteOptions {
  /** Skip if the file already has a secret. Default: false. */
  idempotent?: boolean;
}

/** Seed the .env with a fresh secret + enabled=false. Idempotent by default:
 * if the file already has a secret, the existing value is preserved. */
export function seedEnvFile(path: string = defaultEnvPath(), options: WriteOptions = {}): { created: boolean; path: string } {
  const existing = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (existing) {
    const parsed = parseLines(existing);
    const hasSecret = parsed.some((l) => l.key === SECRET_KEY && l.value.length > 0);
    if (hasSecret && options.idempotent !== false) {
      return { created: false, path };
    }
  }
  const secret = generateSecret();
  writeEnv({ secret, enabled: false }, path);
  return { created: true, path };
}

export function writeEnv(state: { secret: string; enabled: boolean }, path: string = defaultEnvPath()): void {
  const text = renderEnvFile(state);
  writeFileSync(path, text, { mode: 0o600 });
  try {
    chmodSync(path, 0o600);
  } catch {
    // Windows doesn't support chmod; ignore.
  }
  // The new secret invalidates all existing tokens.
  clearAllRevocations();
}

export function getEnvPath(): string {
  return defaultEnvPath();
}

export { SECRET_KEY, ENABLED_KEY };

/** Convenience for the API routes that need to know where to point users
 * after a rotation. */
export function describePath(): { path: string; relative: string } {
  const path = defaultEnvPath();
  const cwd = process.cwd();
  const relative = path.startsWith(cwd) ? path.slice(cwd.length).replace(/^\/+/, "") || "." : path;
  return { path, relative };
}

// Suppress an unused-import warning when callers don't use the `join` import
// directly; it's kept available for future path-joining helpers.
void join;
