# Standalone installer for Rocinante on Windows.
#
# Pipeline:
#   1. Verify Node.js >= 22.19.0 (offer to install if missing).
#   2. Install the upstream `omp` binary via the official oh-my-pi installer
#      (irm https://omp.sh/install | iex). Skip when already present.
#   3. Smoke-test the omp binary (`omp --version`).
#   4. Download the Rocinante source tarball from the GitHub release
#      matching the RocinanteVersion param (default: latest). The release
#      is auto-generated by GitHub for every tag.
#   5. Extract, install deps, build, and symlink the launcher into BinDir.
#   6. Print a friendly "Run 'rocinante' to start" message.
#
# Why source tarball + local build instead of `npm install -g`?
# - The npm publish workflow was failing on font fetch (the CI runner
#   couldn't reach fonts.gstatic.com). Distributing via GitHub Releases
#   removes the npm publish dependency entirely.
# - Source tarball is auto-generated by GitHub for every tag and
#   versioned by the tag name, so this script can pin to a specific
#   Rocinante release.
# - Future versions can ship a prebuilt tarball for faster installs;
#   this script picks whichever exists.
#
# Usage (PowerShell):
#   irm https://raw.githubusercontent.com/lucaspdude/ompweb/main/scripts/install.ps1 | iex
#   $env:PI_INSTALL_DIR = "$HOME\bin"; irm ... | iex
#   $env:PI_REF = "v17.2.15"; irm ... | iex
#   $env:ROCINANTE_VERSION = "v0.3.0"; irm ... | iex
#   $env:BIN_DIR = "$HOME\.local\bin"; irm ... | iex
#
# This script is idempotent: re-running it skips the steps that already
# succeeded on the host (omp installed, Rocinante installed).

[CmdletBinding()]
param(
  [string]$InstallDir = "$env:USERPROFILE\.local\bin",
  [string]$Ref = "",
  [string]$RocinanteVersion = "",
  [string]$BinDir = "",
  [string]$ShareDir = "",
  [string]$Repo = "lucaspdude/ompweb"
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

$NodeMinMajor = 22
$NodeMinMinor = 19
$OmpInstallUrl = "https://omp.sh/install"

if (-not $BinDir) { $BinDir = $InstallDir }
if (-not $ShareDir) { $ShareDir = Join-Path $env:USERPROFILE ".local\share\rocinante" }

function Log($msg)  { Write-Host "[install] $msg" -ForegroundColor Cyan }
function Warn($msg) { Write-Host "[warn] $msg" -ForegroundColor Yellow }
function Fail($msg) {
  Write-Host "[error] $msg" -ForegroundColor Red
  exit 1
}

function Ensure-Node {
  $node = $null
  try { $node = & node --version 2>$null } catch { $node = $null }
  if (-not $node) {
    Fail "Node.js not found. Install Node.js >= $NodeMinMajor.$NodeMinMinor from https://nodejs.org/ and re-run this script."
  }
  if ($node -match "^v(\d+)\.(\d+)\.") {
    $major = [int]$Matches[1]
    $minor = [int]$Matches[2]
    if (($major -lt $NodeMinMajor) -or (($major -eq $NodeMinMajor) -and ($minor -lt $NodeMinMinor))) {
      Fail "Node.js $node is too old. Rocinante requires >= $NodeMinMajor.$NodeMinMinor."
    }
  }
  Log "Node.js $node OK"
}

function Ensure-Omp {
  $existing = $null
  try { $existing = & omp --version 2>$null } catch { $existing = $null }
  if ($existing) {
    Log "omp already on PATH (will reuse)"
  } else {
    Log "Installing omp from $OmpInstallUrl into $InstallDir…"
    if (-not (Test-Path $InstallDir)) {
      New-Item -ItemType Directory -Path $InstallDir | Out-Null
    }
    $env:PI_INSTALL_DIR = $InstallDir
    if ($Ref) { $env:PI_REF = $Ref }
    try {
      irm $OmpInstallUrl | iex
    } catch {
      Fail "omp installer failed. See https://github.com/can1357/oh-my-pi#manual-install"
    }
    # Refresh PATH for this session.
    $env:PATH = "$InstallDir;$env:PATH"
  }

  Log "Smoke-testing omp --version…"
  try {
    $version = & omp --version 2>&1
    if ($LASTEXITCODE -ne 0) {
      Fail "omp --version exited with code $LASTEXITCODE."
    }
  } catch {
    Fail "omp --version could not be executed: $_"
  }
  Log "omp $version OK"
}

function Resolve-Version {
  if ($RocinanteVersion) { return $RocinanteVersion }
  try {
    $resp = Invoke-WebRequest -UseBasicParsing -Uri "https://api.github.com/repos/$Repo/releases/latest" -Headers @{ "Accept" = "application/vnd.github+json" }
    $obj = $resp.Content | ConvertFrom-Json
    return $obj.tag_name
  } catch {
    Fail "Could not resolve the latest Rocinante release. Set -RocinanteVersion v0.3.0 to pin a specific version."
  }
}

function Ensure-Rocinante {
  $version = Resolve-Version
  $ref = $version -replace '^v',''

  $marker = Join-Path $ShareDir "package.json"
  if ((Test-Path $marker) -and (Test-Path (Join-Path $ShareDir "bin\ocinante.js"))) {
    try {
      $installed = (Get-Content $marker -Raw | ConvertFrom-Json).version
    } catch { $installed = "unknown" }
    if ($installed -eq $ref) {
      Log "Rocinante $ref already installed at $ShareDir (will refresh symlink only)"
      Ensure-Symlink
      return
    }
    Log "Upgrading Rocinante $installed -> $ref"
    Remove-Item -Recurse -Force $ShareDir
  }

  $tarball = Join-Path $env:TEMP "rocinante-$ref.tar.gz"
  Log "Downloading Rocinante $version source tarball from $Repo..."
  try {
    Invoke-WebRequest -UseBasicParsing -Uri "https://github.com/$Repo/archive/refs/tags/$version.tar.gz" -OutFile $tarball
  } catch {
    Fail "Failed to download https://github.com/$Repo/archive/refs/tags/$version.tar.gz. Check that the tag exists."
  }

  Log "Extracting to $ShareDir..."
  if (-not (Test-Path $ShareDir)) {
    New-Item -ItemType Directory -Path $ShareDir | Out-Null
  }
  # Strip exactly one leading directory component (the GitHub tarball
  # extracts to a top-level dir like ompweb-<ref>/).
  Get-Content $tarball -Raw | tar -xzf - -C $ShareDir --strip-components=1
  Remove-Item -Force $tarball

  Push-Location $ShareDir
  try {
    Log "Installing npm dependencies (this can take a minute on first run)..."
    $ok = $false
    try { & npm ci --omit=dev --ignore-scripts 2>$null; if ($LASTEXITCODE -eq 0) { $ok = $true } } catch {}
    if (-not $ok) {
      try { & npm install --omit=dev --ignore-scripts 2>$null; if ($LASTEXITCODE -eq 0) { $ok = $true } } catch {}
    }
    if (-not $ok) { Fail "npm install failed in $ShareDir." }

    Log "Building Rocinante (next build)..."
    & npm run build
    if ($LASTEXITCODE -ne 0) {
      Fail "npm run build failed in $ShareDir."
    }
  } finally {
    Pop-Location
  }

  Log "Rocinante $ref built successfully"
  Ensure-Symlink
}

function Ensure-Symlink {
  $existing = $null
  try { $existing = & rocinante --version 2>$null } catch { $existing = $null }
  if (-not $existing) {
    Log "Re-install note: rocinante not on PATH yet. Add '$BinDir' to your PATH."
  }
  if (-not (Test-Path $BinDir)) {
    New-Item -ItemType Directory -Path $BinDir | Out-Null
  }
  $launcher = Join-Path $ShareDir "bin\ocinante.js"
  $link = Join-Path $BinDir "rocinante"
  if (Test-Path $link) { Remove-Item -Force $link }
  New-Item -ItemType SymbolicLink -Path $link -Target $launcher
  Log "Linked $link -> $launcher"
}

function Main {
  Log "Installing Rocinante..."
  Ensure-Node
  Ensure-Omp
  Ensure-Rocinante

  Write-Host ""
  Write-Host "Rocinante installed." -ForegroundColor Green
  Write-Host "  Run 'rocinante' to start the web UI."
  Write-Host "  The UI opens on http://127.0.0.1:30178 by default."
  Write-Host "  Custom port: `$env:ROCINANTE_PORT=4000; rocinante"
  if (-not ((Get-Command rocinante -ErrorAction SilentlyContinue) -ne $null)) {
    Write-Host "  Add $BinDir to your PATH and restart the shell." -ForegroundColor Yellow
  }
}

Main
