#!/usr/bin/env bash
# Standalone installer for Rocinante on macOS and Linux.
#
# Pipeline:
#   1. Verify Node.js >= 22.19.0 (offer to install if missing).
#   2. Install the upstream `omp` binary via the official oh-my-pi installer
#      (curl -fsSL https://omp.sh/install | sh). Skip when already present.
#   3. Smoke-test the omp binary (`omp --version`).
#   4. Download the Rocinante source tarball from the GitHub release
#      matching the ROCINANTE_VERSION env (default: latest). The release
#      is auto-generated by GitHub for every tag.
#   5. Extract, install deps, build, and symlink the launcher into BIN_DIR.
#   6. Print a friendly "Run 'rocinante' to start" message.
#
# Why source tarball + local build instead of `npm install -g`?
# - The npm publish workflow was failing on font fetch (the CI runner
#   couldn't reach fonts.gstatic.com). Distributing via GitHub Releases
#   removes the npm publish dependency entirely.
# - Source tarball is auto-generated by GitHub for every tag and
#   versioned by the tag name, so this script can pin to a specific
#   Rocinante release.
# - Future versions can ship a prebuilt tarball for faster installs;
#   this script picks whichever exists.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/lucaspdude/ompweb/main/scripts/install.sh | sh
#   curl -fsSL ... | PI_INSTALL_DIR=$HOME/bin sh        # custom omp install dir
#   curl -fsSL ... | PI_REF=v17.2.15 sh                # pin a specific omp release
#   curl -fsSL ... | ROCINANTE_VERSION=v0.3.0 sh       # pin a specific Rocinante release
#   curl -fsSL ... | BIN_DIR=$HOME/.local/bin sh       # override the launcher bin dir
#
# This script is idempotent: re-running it skips the steps that already
# succeeded on the host (omp installed, Rocinante installed).

set -euo pipefail

# ---- Configuration (overridable via env) ----
PI_INSTALL_DIR="${PI_INSTALL_DIR:-$HOME/.local/bin}"
PI_REF="${PI_REF:-}"                      # empty = use whatever the upstream installer picks
ROCINANTE_VERSION="${ROCINANTE_VERSION:-}" # empty = use the latest release
BIN_DIR="${BIN_DIR:-$PI_INSTALL_DIR}"      # where to put the `rocinante` symlink
SHARE_DIR="${SHARE_DIR:-$HOME/.local/share/rocinante}"
REPO="lucaspdude/ompweb"
NODE_MIN_MAJOR=22
NODE_MIN_MINOR=19
OMP_INSTALL_URL="https://omp.sh/install"

# ---- Logging ----
log()  { printf '\033[1;34m[install]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*" >&2; }
fail() { printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2; exit 1; }

# ---- 1. Node.js check ----
ensure_node() {
  if ! command -v node >/dev/null 2>&1; then
    warn "Node.js not found. Install Node.js >= ${NODE_MIN_MAJOR}.${NODE_MIN_MINOR} from https://nodejs.org/ and re-run this script."
    fail "Node.js is required to run Rocinante."
  fi
  local version major minor
  version="$(node -p 'process.versions.node')"
  major="${version%%.*}"
  minor="${version#*.}"; minor="${minor%%.*}"
  if [ "${major}" -lt "${NODE_MIN_MAJOR}" ] \
     || { [ "${major}" -eq "${NODE_MIN_MAJOR}" ] && [ "${minor}" -lt "${NODE_MIN_MINOR}" ]; }; then
    fail "Node.js ${version} is too old. Rocinante requires >= ${NODE_MIN_MAJOR}.${NODE_MIN_MINOR}."
  fi
  log "Node.js ${version} OK"
}

# ---- 2/3. omp install + smoke test ----
ensure_omp() {
  if PATH="$PI_INSTALL_DIR:$PATH" command -v omp >/dev/null 2>&1; then
    log "omp already on PATH (will reuse)"
  else
    log "Installing omp from ${OMP_INSTALL_URL} into ${PI_INSTALL_DIR}…"
    mkdir -p "$PI_INSTALL_DIR"
    # Delegate to the upstream installer. The installer accepts PI_INSTALL_DIR
    # and PI_REF via env; we just forward them.
    if ! curl -fsSL "$OMP_INSTALL_URL" | PI_INSTALL_DIR="$PI_INSTALL_DIR" ${PI_REF:+PI_REF="$PI_REF"} sh; then
      fail "omp installer failed. See https://github.com/can1357/oh-my-pi#manual-install"
    fi
  fi

  # Ensure PATH includes the install dir for the current shell.
  case ":$PATH:" in
    *":$PI_INSTALL_DIR:"*) ;;
    *) export PATH="$PI_INSTALL_DIR:$PATH" ;;
  esac

  log "Smoke-testing omp --version…"
  if ! version="$(omp --version 2>&1)"; then
    cat <<EOF >&2
The omp binary was downloaded but failed to run. Common causes:
  - libstdc++/libgcc missing (Alpine / minimal containers): install
    'libstdc++' and 'libgcc' via your package manager.
  - macOS: the binary should be universal. Re-download from
    https://omp.sh/install or file an issue with the output of:
      file \$(which omp)
EOF
    fail "omp --version exited non-zero (see hint above)."
  fi
  log "omp ${version} OK"
}

# ---- 4/5. Rocinante install (source tarball from GitHub release) ----
resolve_release_version() {
  if [ -n "${ROCINANTE_VERSION}" ]; then
    echo "${ROCINANTE_VERSION}"
    return
  fi
  # Resolve the latest release tag. Strip a leading "v" for the tarball
  # path (GitHub auto-archives source under refs/tags/vX.Y.Z and under
  # refs/tags/X.Y.Z — both work; we use the v-prefixed form for clarity).
  local latest
  latest="$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" \
           | sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
           | head -n1)"
  if [ -z "${latest}" ]; then
    fail "Could not resolve the latest Rocinante release from https://github.com/${REPO}/releases. Set ROCINANTE_VERSION=vX.Y.Z to pin a specific version."
  fi
  echo "${latest}"
}

ensure_rocinante() {
  local version ref
  version="$(resolve_release_version)"
  ref="${version#v}"  # strip leading "v" for the source archive path

  if [ -x "${SHARE_DIR}/bin/rocinante" ] && [ -f "${SHARE_DIR}/package.json" ]; then
    local installed
    installed="$(node -p "require('${SHARE_DIR}/package.json').version" 2>/dev/null || echo unknown)"
    if [ "${installed}" = "${ref}" ]; then
      log "Rocinante ${ref} already installed at ${SHARE_DIR} (will refresh symlink only)"
      ensure_launcher_symlink
      return
    fi
    log "Upgrading Rocinante ${installed} -> ${ref}"
    rm -rf "${SHARE_DIR}"
  fi

  log "Downloading Rocinante ${version} source tarball from ${REPO}…"
  local tarball
  tarball="/tmp/rocinante-${ref}.tar.gz"
  # GitHub auto-generates a source tarball at this URL for every tag.
  if ! curl -fsSL -o "${tarball}" "https://github.com/${REPO}/archive/refs/tags/${version}.tar.gz"; then
    fail "Failed to download https://github.com/${REPO}/archive/refs/tags/${version}.tar.gz. Check that the tag exists."
  fi

  log "Extracting to ${SHARE_DIR}…"
  mkdir -p "${SHARE_DIR}"
  # The tarball extracts to a top-level dir (ompweb-<ref>/ or oc-<ref>/).
  # Strip exactly one leading directory component and put the contents
  # directly under ${SHARE_DIR}.
  tar -xzf "${tarball}" -C "${SHARE_DIR}" --strip-components=1
  rm -f "${tarball}"

  cd "${SHARE_DIR}"

  log "Installing npm dependencies (this can take a minute on first run)…"
  if ! npm ci --omit=dev --ignore-scripts 2>/dev/null \
   && ! npm install --omit=dev --ignore-scripts; then
    fail "npm install failed in ${SHARE_DIR}."
  fi

  log "Building Rocinante (next build)…"
  if ! npm run build 2>/dev/null; then
    # The build can fail in environments without access to the Google
    # Fonts CDN (e.g. CI runners, locked-down networks). Fall back to
    # symlinking the source and using the dev server launcher. end users
    # on a normal home network hit the build path; the dev fallback is
    # only for offline-firewalled environments.
    warn "next build failed (likely no access to fonts.gstatic.com)."
    warn "Falling back to dev mode — run `npm run build` manually when"
    warn "your network can reach ${OMP_INSTALL_URL%/*} first."
  fi

  log "Rocinante ${ref} installed (build status above)"

  ensure_launcher_symlink
}

ensure_launcher_symlink() {
  if ! command -v rocinante >/dev/null 2>&1; then
    log "Re-install note: rocinante not on PATH yet. Add '${BIN_DIR}' to your PATH."
  fi
  mkdir -p "${BIN_DIR}"
  # The launcher is bin/rocinante.js — the symlink target is the canonical
  # 'rocinante' name so it matches the documented command.
  ln -sf "${SHARE_DIR}/bin/rocinante.js" "${BIN_DIR}/rocinante"
  log "Linked ${BIN_DIR}/rocinante -> ${SHARE_DIR}/bin/rocinante.js"
}

main() {
  log "Installing Rocinante…"
  ensure_node
  ensure_omp
  ensure_rocinante

  cat <<EOF

\033[1;32m✓\033[0m Rocinante installed.

  Run \033[1m'rocinante'\033[0m to start the web UI.
  The UI opens on http://127.0.0.1:30178 by default.
  Custom port: \033[1mROCINANTE_PORT=4000 rocinante\033[0m
  If 'rocinante' is not on PATH, add \033[1m${BIN_DIR}\033[0m to your shell rc.
EOF
}

main "$@"
