#!/usr/bin/env bash
# Standalone installer for Rocinante on macOS and Linux.
#
# Pipeline:
#   1. Verify Node.js >= 22.19.0 (offer to install if missing).
#   2. Install the upstream `omp` binary via the official oh-my-pi installer
#      (curl -fsSL https://omp.sh/install | sh). Skip when already present.
#   3. Smoke-test the omp binary (`omp --version`).
#   4. Download the Rocinante source tarball from the GitHub release
#      matching the ROCINANTE_VERSION env (default: latest). The release
#      is auto-generated by GitHub for every tag.
#   5. Extract, install deps, build, and symlink the launcher into BIN_DIR.
#   6. Print a friendly "Run 'rocinante' to start" message.
#
# Why source tarball + local build instead of `npm install -g`?
# - The npm publish workflow was failing on font fetch (the CI runner
#   couldn't reach fonts.gstatic.com). Distributing via GitHub Releases
#   removes the npm publish dependency entirely.
# - Source tarball is auto-generated by GitHub for every tag and
#   versioned by the tag name, so this script can pin to a specific
#   Rocinante release.
# - Future versions can ship a prebuilt tarball for faster installs;
#   this script picks whichever exists.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/lucaspdude/rocinante/main/scripts/install.sh | sh
#   curl -fsSL ... | PI_INSTALL_DIR=$HOME/bin sh        # custom omp install dir
#   curl -fsSL ... | PI_REF=v17.2.15 sh                # pin a specific omp release
#   curl -fsSL ... | ROCINANTE_VERSION=v0.3.0 sh       # pin a specific Rocinante release
#   curl -fsSL ... | BIN_DIR=$HOME/.local/bin sh       # override the launcher bin dir
#
# This script is idempotent: re-running it skips the steps that already
# succeeded on the host (omp installed, Rocinante installed).

set -euo pipefail

# ---- Configuration (overridable via env) ----
PI_INSTALL_DIR="${PI_INSTALL_DIR:-$HOME/.local/bin}"
PI_REF="${PI_REF:-}"                      # empty = use whatever the upstream installer picks
ROCINANTE_VERSION="${ROCINANTE_VERSION:-}" # empty = use the latest release
BIN_DIR="${BIN_DIR:-$PI_INSTALL_DIR}"      # where to put the `rocinante` symlink
SHARE_DIR="${SHARE_DIR:-$HOME/.local/share/rocinante}"
REPO="lucaspdude/rocinante"
NODE_MIN_MAJOR=22
NODE_MIN_MINOR=19
OMP_INSTALL_URL="https://omp.sh/install"
# Install the systemd / launchd service so Rocinante auto-starts on
# boot and auto-restarts on crash. Set ROCINANTE_INSTALL_SERVICE=0 to opt
# out (e.g. on a transient host or CI). Default-on matches the user's
# expectation that the server is \"always working\".
ROCINANTE_INSTALL_SERVICE="${ROCINANTE_INSTALL_SERVICE:-1}"
ROCINANTE_PORT="${ROCINANTE_PORT:-30177}"
# ---- Logging ----
log()  { printf '\033[1;34m[install]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*" >&2; }
fail() { printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2; exit 1; }

# ---- 1. Node.js check ----
ensure_node() {
  if ! command -v node >/dev/null 2>&1; then
    warn "Node.js not found. Install Node.js >= ${NODE_MIN_MAJOR}.${NODE_MIN_MINOR} from https://nodejs.org/ and re-run this script."
    fail "Node.js is required to run Rocinante."
  fi
  local version major minor
  version="$(node -p 'process.versions.node')"
  major="${version%%.*}"
  minor="${version#*.}"; minor="${minor%%.*}"
  if [ "${major}" -lt "${NODE_MIN_MAJOR}" ] \
     || { [ "${major}" -eq "${NODE_MIN_MAJOR}" ] && [ "${minor}" -lt "${NODE_MIN_MINOR}" ]; }; then
    fail "Node.js ${version} is too old. Rocinante requires >= ${NODE_MIN_MAJOR}.${NODE_MIN_MINOR}."
  fi
  log "Node.js ${version} OK"
}

# ---- 2/3. omp install + smoke test ----
ensure_omp() {
  if PATH="$PI_INSTALL_DIR:$PATH" command -v omp >/dev/null 2>&1; then
    log "omp already on PATH (will reuse)"
  else
    log "Installing omp from ${OMP_INSTALL_URL} into ${PI_INSTALL_DIR}…"
    mkdir -p "$PI_INSTALL_DIR"
    # Delegate to the upstream installer. The installer accepts PI_INSTALL_DIR
    # and PI_REF via env; we just forward them.
    if ! curl -fsSL "$OMP_INSTALL_URL" | PI_INSTALL_DIR="$PI_INSTALL_DIR" ${PI_REF:+PI_REF="$PI_REF"} sh; then
      fail "omp installer failed. See https://github.com/can1357/oh-my-pi#manual-install"
    fi
  fi

  # Ensure PATH includes the install dir for the current shell.
  case ":$PATH:" in
    *":$PI_INSTALL_DIR:"*) ;;
    *) export PATH="$PI_INSTALL_DIR:$PATH" ;;
  esac

  log "Smoke-testing omp --version…"
  if ! version="$(omp --version 2>&1)"; then
    cat <<EOF >&2
The omp binary was downloaded but failed to run. Common causes:
  - libstdc++/libgcc missing (Alpine / minimal containers): install
    'libstdc++' and 'libgcc' via your package manager.
  - macOS: the binary should be universal. Re-download from
    https://omp.sh/install or file an issue with the output of:
      file \$(which omp)
EOF
    fail "omp --version exited non-zero (see hint above)."
  fi
  log "omp ${version} OK"
}

# ---- 4/5. Rocinante install (source tarball from GitHub release) ----
resolve_release_version() {
  if [ -n "${ROCINANTE_VERSION}" ]; then
    echo "${ROCINANTE_VERSION}"
    return
  fi
  # Resolve the latest release tag. Strip a leading "v" for the tarball
  # path (GitHub auto-archives source under refs/tags/vX.Y.Z and under
  # refs/tags/X.Y.Z — both work; we use the v-prefixed form for clarity).
  local latest
  latest="$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" \
           | sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
           | head -n1)"
  if [ -z "${latest}" ]; then
    fail "Could not resolve the latest Rocinante release from https://github.com/${REPO}/releases. Set ROCINANTE_VERSION=vX.Y.Z to pin a specific version."
  fi
  echo "${latest}"
}

ensure_rocinante() {
  local version ref
  version="$(resolve_release_version)"
  ref="${version#v}"  # strip leading "v" for the source archive path

  if [ -x "${SHARE_DIR}/bin/rocinante" ] && [ -f "${SHARE_DIR}/package.json" ]; then
    local installed
    installed="$(node -p "require('${SHARE_DIR}/package.json').version" 2>/dev/null || echo unknown)"
    if [ "${installed}" = "${ref}" ]; then
      log "Rocinante ${ref} already installed at ${SHARE_DIR} (will refresh symlink only)"
      ensure_launcher_symlink
      return
    fi
    log "Upgrading Rocinante ${installed} -> ${ref}"
    rm -rf "${SHARE_DIR}"
  fi

  log "Downloading Rocinante ${version} source tarball from ${REPO}…"
  local tarball
  tarball="/tmp/rocinante-${ref}.tar.gz"
  # GitHub auto-generates a source tarball at this URL for every tag.
  if ! curl -fsSL -o "${tarball}" "https://github.com/${REPO}/archive/refs/tags/${version}.tar.gz"; then
    fail "Failed to download https://github.com/${REPO}/archive/refs/tags/${version}.tar.gz. Check that the tag exists."
  fi

  log "Extracting to ${SHARE_DIR}…"
  mkdir -p "${SHARE_DIR}"
  # The tarball extracts to a top-level dir (ompweb-<ref>/ or oc-<ref>/).
  # Strip exactly one leading directory component and put the contents
  # directly under ${SHARE_DIR}.
  tar -xzf "${tarball}" -C "${SHARE_DIR}" --strip-components=1
  rm -f "${tarball}"

  cd "${SHARE_DIR}"

  log "Installing npm dependencies (this can take a minute on first run)…"
  # Install devDependencies too: `next build` needs @tailwindcss/postcss +
  # typescript + the other devDependencies. Without them the build aborts
  # with "Cannot find module '@tailwindcss/postcss'" and the install script
  # silently falls back to dev mode (which then can't render UI on a
  # loopback install). The font fetch is still network-dependent and falls
  # back to local via the existing dev-fallback branch.
  if ! npm ci --ignore-scripts 2>/dev/null \
   && ! npm install --ignore-scripts; then
    fail "npm install failed in ${SHARE_DIR}."
  fi

  log "Building Rocinante (next build)…"
  if ! npm run build 2>/dev/null; then
    # The build can fail in environments without access to the Google
    # Fonts CDN (e.g. CI runners, locked-down networks). Fall back to
    # symlinking the source and using the dev server launcher. end users
    # on a normal home network hit the build path; the dev fallback is
    # only for offline-firewalled environments.
    warn "next build failed (likely no access to fonts.gstatic.com)."
    warn "Falling back to dev mode — run `npm run build` manually when"
    warn "your network can reach ${OMP_INSTALL_URL%/*} first."
  fi
  seed_env_file
  log "Rocinante ${ref} installed (build status above)"

  ensure_launcher_symlink
}

ensure_launcher_symlink() {
  mkdir -p "${BIN_DIR}"
  # The launcher is bin/rocinante.js — the symlink target is the canonical
  # 'rocinante' name so it matches the documented command.
  ln -sf "${SHARE_DIR}/bin/rocinante.js" "${BIN_DIR}/rocinante"
  log "Linked ${BIN_DIR}/rocinante -> ${SHARE_DIR}/bin/rocinante.js"
  # Also link into /usr/local/bin (always on PATH for non-interactive
  # login shells) so `rocinante` works out-of-the-box without sourcing
  # rc files. Best-effort: skip silently if the dir is not writable.
  if [ -d /usr/local/bin ] && [ -w /usr/local/bin ]; then
    ln -sf "${SHARE_DIR}/bin/rocinante.js" /usr/local/bin/rocinante
    log "Linked /usr/local/bin/rocinante -> ${SHARE_DIR}/bin/rocinante.js"
  fi
}

ensure_systemd_service() {
  # Set up a user-level systemd service so Rocinante auto-starts on boot
  # and auto-restarts on crash. `systemctl --user` works for any user
  # (including root) without needing /etc/systemd permissions.
  local unit_dir="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
  local unit_path="${unit_dir}/rocinante.service"
  mkdir -p "${unit_dir}"
  cat > "${unit_path}" <<UNIT
[Unit]
Description=Rocinante web UI for the omp coding agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${SHARE_DIR}
ExecStart=${SHARE_DIR}/bin/rocinante.js
Environment=ROCINANTE_PORT=${ROCINANTE_PORT}
EnvironmentFile=-${SHARE_DIR}/.env
Restart=always
RestartSec=5
TimeoutStopSec=20

[Install]
WantedBy=default.target
UNIT
  if [ -n "${XDG_RUNTIME_DIR:-}" ] && systemctl --user status >/dev/null 2>&1; then
    systemctl --user daemon-reload
    systemctl --user enable rocinante.service
    systemctl --user restart rocinante.service
    log "systemd user service enabled and started (${unit_path})"
  else
    log "Wrote ${unit_path}; enable with: systemctl --user enable --now rocinante.service"
  fi
}

ensure_launchd_agent() {
  # macOS: install a per-user LaunchAgent that keeps the server running
  # after the user logs in. launchd auto-restarts on crash.
  local plist_dir="$HOME/Library/LaunchAgents"
  local plist_path="${plist_dir}/com.lucaspdude.rocinante.plist"
  mkdir -p "${plist_dir}"
  cat > "${plist_path}" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.lucaspdude.rocinante</string>
  <key>ProgramArguments</key>
  <array>
    <string>${SHARE_DIR}/bin/rocinante.js</string>
  </array>
  <key>WorkingDirectory</key><string>${SHARE_DIR}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>ROCINANTE_PORT</key><string>${ROCINANTE_PORT}</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
</dict>
</plist>
PLIST
  launchctl load -w "${plist_path}" 2>/dev/null || true
  log "launchd LaunchAgent installed (${plist_path})"
}

main() {
  log "Installing Rocinante…"
  ensure_node
  ensure_omp
  ensure_rocinante
  ensure_launcher_symlink

  if [ "${ROCINANTE_INSTALL_SERVICE}" = "1" ]; then
    case "$(uname -s)" in
      Linux)  ensure_systemd_service ;;
      Darwin) ensure_launchd_agent ;;
      *)      log "Auto-start not supported on $(uname -s); skipping service install." ;;
    esac
  fi

  cat <<EOF

\033[1;32m✓\033[0m Rocinante installed.

  Run \`rocinante\` to start the web UI.
  The UI opens on http://127.0.0.1:${ROCINANTE_PORT} by default.
  If 'rocinante' is not on PATH, add \033[1m${BIN_DIR}\033[0m to your shell rc.
  A symlink was also placed in \033[1m/usr/local/bin\033[0m (always on PATH).
EOF

  seed_env_file
}

seed_env_file() {
  local env_path="${SHARE_DIR}/.env"
  if [ -f "${env_path}" ]; then
    log ".env already present at ${env_path} (will not overwrite)"
    return 0
  fi
  local secret
  if command -v openssl >/dev/null 2>&1; then
    secret="$(openssl rand -base64 32)"
  else
    secret="$(head -c 32 /dev/urandom | base64)"
  fi
  {
    printf '# Generated by Rocinante install on %s. Do not edit by hand\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '# unless you know what you are doing — see docs/in-progress/2026-08-13-access-key-protection.md\n'
    printf 'ROCINANTE_SECRET=%s\n' "${secret}"
    printf 'ROCINANTE_AUTH_ENABLED=false\n'
  } > "${env_path}"
  chmod 600 "${env_path}" 2>/dev/null || true
  log "Seeded .env at ${env_path} (ROCINANTE_AUTH_ENABLED=false)"
}

main "$@"
